version: '3.9'
services:
  database:
    image: 'postgres:13.3-alpine' # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - '${DB_PORT:-5432}:${DB_PORT:-5432}'
    networks:
      - api_server_default
  api:
    networks:
      - api_server_default
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
      - api.env
    ports:
      - '${API_PORT:-4000}:${API_PORT:-4000}'
    links:
        - database
    depends_on: 
        - database
volumes:
  database-data: # named volumes can be managed easier using docker-compose
networks:
  api_server_default:
    driver: bridge